### ISSUE TITLE
If an exception occurs in `get_blocked_ip`, nothing will be returned

### ISSUE THREAD

**Issue by TheTechRobo** [BeeHiveCyberSecurity/WAF-IPDB#4]
There is this code in `get_blocked_ip`:

```
  except Exception as e:
      # If there is an exception, call the function recursively
    get_blocked_ip()
```

I think this should be `return get_blocked_ip()` rather than `get_blocked_ip() because otherwise it will retry but return nothing.

**Comment by BeeHiveSafety** [comment]
We've made updates to this codebase, apologies for the delay.
